### ISSUE TITLE
Animation Problems with animated AwesomeWM widgets

### ISSUE THREAD

**Issue by paulhersch** [dccsillag/picom#23]
I use AwesomeWM and animate some widgets with rubato (a plugin for awesome).
However, the widgets in question do flicker a lot when animated. Is there an option to exclude certain window types from being animated?

**Comment by dccsillag** [comment]
I think what we need is implemented in @pijulius' PR: https://github.com/dccsillag/picom/pull/22. Unfortunately there are still some things which we need to solve before merging it, but it might be of help.

On the other hand, could you describe a bit more this flickering? Maybe record a video of it? Excluding certain window types is a workaround, ideallly we'd solve it so that we don't have such issues at all.

**Comment by paulhersch** [comment]
https://user-images.githubusercontent.com/74120050/140542860-ad56ac0d-88cf-4983-80bc-df92bcf01cec.mp4

here is a video of how it looks for me (shitty quality cuz compression)
It is a little worse for me because the video is shot with 30 fps and i have a 144Hz screen
also the selective excluding of animations would be good because the animations from picom are overriding the ones i set

**Comment by pijulius** [comment]
Hi Guys, disabling animation all together for those things doesn't help?:

wintypes:
{
  toolbar = { animation = "none"; }
};


just guessing as not sure what type those windows are but xprop should help to check it and then disabling animations for them.

**Comment by paulhersch** [comment]
closing this as it is fixable with excluding win types from animation
