### ISSUE TITLE
Artifacts (but only on one specific screen)

### ISSUE THREAD

**Issue by DesjardinsRepos** [dccsillag/picom#49]
Here ive got a quite weird issue. [Video](https://www.youtube.com/watch?v=z0s9dZdfRzo)
~~This only happens on one of my 3 monitors.~~ Now on every one of them
This only happens with some applications, around every third application is affected (for example spotify, basically all electron apps, firefox too, but only on some websites, ...)

Specs:
Arch x64
i3-gaps
rx 5700, xf86-video-amdgpu 22.0.0-1, mesa 22.1.7-1
picom-animations-git 1770_Next.208.g51b2135_2022.05.29-1
[config](https://github.com/DesjardinsRepos/home-files-public/blob/master/dotfiles/picom/conf) 
[glxinfo -B](https://pastebin.com/00N0XaXy)
[picom --diagnostics](https://pastebin.com/UYBy5PcW)

**Comment by dccsillag** [comment]
If I'm not mistaken, this is happening because you are running on the legacy backends, where we haven't properly implemented window pixmap resizing. I.e., if you run with `picom --experimental-backends`, then you should not see this.

We won't be implementing those for the legacy backends, rationale for that decision is here: https://github.com/dccsillag/picom/issues/3#issuecomment-888619106. In fact, if I'm not mistaken, upstream Picom actually is now using the "--experimental-backends" backends as default.

If you can check that this is indeed because of the legacy backends, then we can close this.

**Comment by DesjardinsRepos** [comment]
Youre right, using experimental-backends did fix this issue.
Thank you for your time!

**Comment by dccsillag** [comment]
Cheers!
