### ISSUE TITLE
Link React-spring visualizer in readme.md

### ISSUE THREAD

**Issue by lonkaars** [dccsillag/picom#5]
I'm not sure if your implementation of spring physics is the same as react-spring, but if it is [react spring visualizer](https://react-spring-visualizer.com/) would be a good thing to link in your readme. It visualizes the animation curve before you put it in your ~/.config/picom.conf

**Comment by dccsillag** [comment]
Unfortunately, react-spring's code has a waay too much boilerplate and options for me to be confident in what it's really doing, but I think it's about the same.
Point is, it may indeed be a good idea to point towards this visualizer (really cool BTW!).

The thing is, I'm not so confident about touching the README, because we want this repo to be ready to PR.
So I'm not really sure where to add that, but I'm thinking of the manpage/asciidoc. So I guess this goes with https://github.com/dccsillag/picom/issues/4.

Thoughts?

**Comment by lonkaars** [comment]
Ooh, I thought this was just going to be another picom fork. I also think it would be better not to touch the readme, but instead put it in the man pages along with the config options.

**Comment by dccsillag** [comment]
Done.
